spring:
  application:
    name: health-global-admin
  datasource:
    url: jdbc:postgresql://${APP_POSTGRES_HOST}:${APP_POSTGRES_PORT}/${APP_POSTGRES_DB}
    username: ${APP_POSTGRES_USER}
    password: ${APP_POSTGRES_PASS}
  flyway:
    locations: classpath:db/migration
  jpa:
    open-in-view: false

server:
  port: ${APP_SERVER_PORT}
